apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service
  labels:
    app: staff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      containers:
      - name: staff-service
        image: praj0080/bestbuy-staff-service:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: staff-service
spec:
  type: LoadBalancer
  selector:
    app: staff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
